# Generated by Django 4.2.1 on 2026-05-29 06:03

from django.db import migrations, models
import django.db.models.deletion
import irezumi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мотива')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('content', models.TextField(blank=True, verbose_name='Легенда и значение')),
                ('image', models.ImageField(blank=True, null=True, upload_to=irezumi.models.get_image_path, verbose_name='Изображение мотива')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Статус публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motifs', to='irezumi.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='motifs', to='irezumi.tagpost', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Мотив',
                'verbose_name_plural': 'Мотивы',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='irezumi_mot_time_cr_765bc4_idx')],
            },
        ),
    ]
