# Generated by Django 4.2.1 on 2026-06-09 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irezumi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motif',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_motifs', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='motif',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_motifs', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время написания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='irezumi.motif', verbose_name='Мотив')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-time_create'],
            },
        ),
    ]
