# Generated by Django 4.2.1 on 2026-05-29 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название студии')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес (Город)')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя мастера')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('century', models.IntegerField(verbose_name='Век')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('studio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='masters.studio', verbose_name='Студия')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['century', 'name'],
            },
        ),
    ]
